### ISSUE TITLE
cnv_summary_plot function

### ISSUE THREAD

**Issue by gersonjr** [JH-Zhou/HandyCNV#14]
**Describe the bug**
Dear Dr. JH-Zhou,

I kept following the HandyCNV R vignette, and I am trying now to use `cnv_summary_plot` function. 
It is running without any error, but this is what I get from it. 

![image](https://user-images.githubusercontent.com/14200208/137344322-fbad9757-cf05-461d-b381-f4ea7d912771.png)

Plot “a” has a `NA` bin, and plot  “d” seems that it’s not getting the y-axis properly. 

Any suggestion?

Thank you!

**Comment by JH-Zhou** [comment]
Hi Gerson, could you please present the ```length_group```  in _cnv_summary_plot()_ you assigned? The ```Na``` in Plot 'a' should related to the ```length_group``` argument.

The plot 'd' seems correct. The y-axis in plot 'd' present the number of samples that has the same number of CNVs were detected. Are there 19 samples in your dataset? the bar with 2.0 on y-axis means there are two samples are contains 42 CNVs. 

Could you please add ```plot_sum_2 = TRUE``` in _cnv_summary_plot()_ to see if this figures correct?

**Comment by JH-Zhou** [comment]
Hi Gerson, the problem of ```NA in plot a``` was fixed. 

The decimal label of ```y-axis in plot d``` is bit tricky, but the plot is correct. I miscounted the samples in last comment, it was 21. 

You can use ```remotes::install_github(repo = "JH-Zhou/HandyCNV")``` to re-install this package to use it, thanks!
